log_level: 20  # INFO

credentials:
  app_key: "INSERT ABC FITNESS APP KEY"
  app_id: "INSERT ABC FITNESS APP ID"
  club_id: "INSERT ABC FITNESS CLUB ID"
  camio_api_token: "INSERT CAMIO DEV TOKEN"

urls:
  camio_domain: "incoming.integrations.camio.com"
  skip_ssl_verification: false

requests:
  devices:
    polling_interval: 43200  # in seconds, how frequently to request station information via the ABC Fitness API. Defaults to every 12 hours

  pacs:
    backoff_multiplier: 2.0  # multiplier for increasing sleep between retries
    backoff_start: 2.0  # initial seconds until retry, gets multiplied by backoff_multiplier after each attempt
    backoff_limit: 3  # max number of retries

  events:
    streaming: false  # ABC Fitness API does not support streaming
    polling_interval: 43200  # in seconds, how frequently to request checkin information via the ABC Fitness API. Defaults to every 12 hours
    count_reset_interval: 86400  # reset the events count every 24 hours
    timezone_offset:  # Timezone offset for the timestamps of the events. Format is +/-HHMM. Examples: -0700, +0100. Does not account for daylight savings time, since the number is always added/subtracted from the UTC time. Default is None.
    timezone_name: "UTC"  # Name of the timezone that the event timestamps are in. Uses pytz timezones. If timezone_offset is also passed, will use the offset over the timezone name. Should account for daylight savings. Examples: US/Central, US/Eastern, US/Pacific, Europe/Paris. Default is UTC.
    get_member_info: true
    page_size: 100

  members:
    page_size: 100

container:
  image: us-central1-docker.pkg.dev/camiologger/public-containers/camio-integration-driver-abc-fitness:latest-linux-amd64

# Note: Can supply no more than three nameservers
dns:
#  - 1.1.1.1
#  - 2.2.2.2
#  - 3.3.3.3