apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: driver
  name: driver
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: driver
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: driver
    spec:
      containers:
        - command:
            - python3
            - /app/abc_fitness.py
            - --config
            - /opt/configs/abc_fitness_config.yaml
          image: {{ .Values.container.image }}
          name: driver
          resources: {}
          volumeMounts:
            - mountPath: /opt/configs
              name: driver-cm0
      restartPolicy: Always
      volumes:
        - configMap:
            name: driver-cm0
          name: driver-cm0
      {{ if .Values.dns }}dnsPolicy: "Default"{{ else }}dnsPolicy: "ClusterFirst"{{ end }}
      {{ if .Values.dns }}dnsConfig:
        nameservers:
          {{- range .Values.dns }}
          - {{ . | title }}
          {{- end }}
      {{ end }}
status: {}
