version: '3.8'

services:

  driver:
    image: us-central1-docker.pkg.dev/camiologger/public-containers/camio-integration-driver-abc-fitness:latest-linux-amd64
    restart: on-failure
    entrypoint: "python3 /app/abc_fitness.py --config /opt/configs/abc_fitness_config.yaml"
    volumes:
      - ./configs/production:/opt/configs